//! Asset module — parsers for all MM6 data formats, with a flat re-export API surface.
pub mod provider;

#[cfg(test)]
pub fn test_lod() -> Option<crate::Assets> {
    crate::Assets::new(crate::get_data_path()).ok()
}

pub mod actor_enums;
pub mod autonotes;
pub mod awards;
pub mod billboard;
pub mod blv;
pub mod blv_builder;
pub mod blv_types;
pub mod bsp_model;
pub mod class;
pub mod dchest;
pub mod ddeclist;
pub mod ddm;
pub mod dift;
pub mod dlv;
pub mod dmonlist;
pub mod dobjlist;
pub mod door_enums;
pub mod doverlay;
pub mod dpft;
pub mod dsft;
pub mod dsounds;
pub mod dtile;
pub mod enums;
pub mod event_enums;
pub mod evt;
pub mod face_enums;
pub mod font;
pub mod image;
pub mod items;
pub mod lod_data;
pub mod mapstats;
pub mod media_cache;
pub mod merchant;
pub mod monsters;
pub mod npcbtb;
pub mod npcnames;
pub mod npcnews;
pub mod npcprof;
pub mod npctext;
pub mod npctopic;
pub mod odm;
pub mod palette;
pub mod passwords;
pub mod pcx;
pub mod proftext;
pub mod quests;
pub mod scroll;
pub mod smk;
pub mod snd;
pub mod sound_enums;
pub mod spells;
pub mod sprite_enums;
pub mod stats;
pub mod terrain;
pub mod tft;
pub mod trans;
pub mod twodevents;
pub mod zlib;

pub use self::blv::{Blv, BlvDoor, DoorState};
pub use self::ddm::{CommonMonsterProps, Ddm, DdmActor};
pub use self::enums::*;
pub use self::evt::EvtFile;
pub use self::font::Font;
pub use self::image::{Image, get_atlas};
pub use self::items::ItemsTable;
pub use self::lod_data::LodData;
pub use self::mapstats::MapStats;
pub use self::media_cache::MediaCache;
pub use self::odm::{Odm, SpawnPoint};
pub use self::palette::{Palette, Palettes};
pub use self::provider::archive::smk::{SmkArchive, SmkWriter};
pub use self::provider::{Archive, ArchiveEntry, LodArchive, LodWriter, StaticGameData as GameData, Version};
pub use self::smk::{SmkAudioInfo, SmkDecoder, SmkInfo, parse_smk_info};
pub use self::snd::SndArchive;
pub use self::zlib::*;

// Re-export specific types
pub use self::actor_enums::AIState;
pub use self::autonotes::AutonotesTable;
pub use self::awards::AwardsTable;
pub use self::billboard::BillboardData;
pub use self::bsp_model::BSPModel;
pub use self::class::ClassTable;
pub use self::dlv::Dlv;
pub use self::dmonlist::MonsterList;
pub use self::dtile::{Dtile, TileTable};
pub use self::merchant::MerchantTable;
pub use self::npcbtb::NpcBtbTable;
pub use self::npcnames::NpcNamePools;
pub use self::npcnews::NpcNewsTable;
pub use self::npcprof::NpcProfTable;
pub use self::npctext::NpcTextTable;
pub use self::npctopic::NpcTopicTable;
pub use self::passwords::PasswordsTable;
pub use self::proftext::ProfTextTable;
pub use self::provider::actors::Actors;
pub use self::provider::decorations::Decorations;
pub use self::provider::lod_decoder::LodDecoder;
pub use self::provider::monster::Monsters;
pub use self::provider::npc::{GeneratedNpc, NpcEntry, StreetNpcs};
pub use self::quests::QuestNames;
pub use self::scroll::ScrollTable;
pub use self::spells::SpellsTable;
pub use self::stats::StatsTable;
pub use self::trans::TransTable;
pub use self::twodevents::TwoDEvents;
